insert into EXCHANGE_RATE (COUNTRY_CODE, CONVERSION_FACTOR) values ('IN', '68.32');
insert into EXCHANGE_RATE (COUNTRY_CODE, CONVERSION_FACTOR) values ('MX', '19.15');
insert into EXCHANGE_RATE (COUNTRY_CODE, CONVERSION_FACTOR) values ('UK', '0.69');	